// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhycY8sICuZ1TpcCLviqZNoeA70pCdwk',
    appId: '1:996186888822:web:2df81d5a08805df9ad9d57',
    messagingSenderId: '996186888822',
    projectId: 'minnews-83ffb',
    authDomain: 'minnews-83ffb.firebaseapp.com',
    storageBucket: 'minnews-83ffb.appspot.com',
    measurementId: 'G-WFRTC617B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8p9fsISIQRP-TygEJWOPGhVBWmi7j_v4',
    appId: '1:996186888822:android:cf21ebeecbe5b02bad9d57',
    messagingSenderId: '996186888822',
    projectId: 'minnews-83ffb',
    storageBucket: 'minnews-83ffb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrwNx7qWBfiCHd0yn9jlXncSeT-flEH0',
    appId: '1:996186888822:ios:705ea0f03838eae6ad9d57',
    messagingSenderId: '996186888822',
    projectId: 'minnews-83ffb',
    storageBucket: 'minnews-83ffb.appspot.com',
    iosClientId: '996186888822-qvgv71i55ghg1ctmiua4644j0i08oq0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrwNx7qWBfiCHd0yn9jlXncSeT-flEH0',
    appId: '1:996186888822:ios:a8a942f195eff201ad9d57',
    messagingSenderId: '996186888822',
    projectId: 'minnews-83ffb',
    storageBucket: 'minnews-83ffb.appspot.com',
    iosClientId: '996186888822-ui78nr4ngn0ogg02uv48nu9kvs4k4mpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
